### PR TITLE
Dark mode diagrams

### PR DESCRIPTION
**Pull request by heeckhau**
image
image

### CODE REVIEW

**Review by th4s — CHANGES_REQUESTED** [review]
This PR includes changes to the `introduction.md`, which probably is an accident?

Otherwise :+1:

**Comment by heeckhau** [comment]
> This PR includes changes to the `introduction.md`, which probably is an accident?
> 
> Otherwise 👍

Indeed. Fixing it now

**Review by th4s — APPROVED** [review]
nice :rocket:

**Comment by heeckhau** [comment]
> 

My changes could not be easily merged because the diagrams had other changes. Fixed now

**Pull request merged**
