### PR TITLE
small fixes

### PR DESCRIPTION
**Pull request by heeckhau**

### CODE REVIEW

**Comment by themighty1** [comment]
I could only get the book to compile when I installed
`cargo install mdbook --version 0.4.22`
We had the same problem before https://discord.com/channels/974410303255232542/1046817286440366120/1047071480611082280

Is it just me?

**Comment by themighty1** [comment]
I mean neither
`cargo install mdbook --version 0.4.29` nor
`cargo install mdbook --version 0.4.21` worked for me

**Comment by heeckhau** [comment]
0.4.21 did not work for me, so I replaced it the most recent version at the time.

The most recent versions today are v0.4.32 (mdbook) and v0.5.5 (mdbook-katex).
Maybe we can simply drop the version?

**Review by themighty1 — APPROVED** [review]
ack

**Pull request merged**
